apiVersion: v1
kind: Pod
metadata:
  name: 200mb-10sec
  labels:
    app: myapp
spec:
  restartPolicy: Never
  containers:
  - name: myapp-container
    image: lawrencegripper/big:200mb
    command: ['sh', '-c', 'sleep 10']
  initContainers:
  - name: init-myservice
    image: gcr.io/google-containers/busybox
    command: ['sh', '-c', 'sleep 10']