apiVersion: v1
kind: Pod
metadata:
  name: 600mb-10sec
  labels:
    app: myapp
spec:
  restartPolicy: Never
  containers:
  - name: myapp-container
    image: lawrencegripper/big:600mb
    command: ['sh', '-c', 'sleep 10']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 10']