apiVersion: v1
kind: Pod
metadata:
  name: control
  labels:
    app: myapp
spec:
  restartPolicy: Never
  containers:
  - name: myapp-container
    image: ubuntu
    command: ['sh', '-c', 'sleep 10']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 10']