apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: ubuntu
    command: ['sh', '-c', 'sleep 3600']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 10']
  - name: init-mydb
    image: conda/miniconda3:latest
    command: ['sh', '-c', 'sleep 15']